name: Despliegue Android por Etiquetas (Tags)

on:
  push:
    tags:
      - 'v*'

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del proyecto
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calcular variables de versión
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "VERSION_NAME=$TAG_NAME" >> $GITHUB_ENV
          COMMITS_ACTUALES=$(git rev-list --count HEAD)
          VERSION_CODE=$((COMMITS_ACTUALES + 70))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependencias de JavaScript
        run: npm ci

      - name: Generar Bundle de Expo
        run: npx expo export:embed --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

      - name: Reconstruir Keystore de producción
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/mi-clave-subida.keystore

      - name: Reconstruir JSON de Google Play
        run: |
          echo "${{ secrets.GOOGLE_PLAY_API_JSON }}" > android/app/google-play-key.json

      - name: Ejecutar Fastlane Deployment
        working-directory: android
        env:
          MYAPP_RELEASE_STORE_FILE: "mi-clave-subida.keystore"
          MYAPP_RELEASE_KEY_ALIAS: "${{ secrets.ANDROID_KEY_ALIAS }}"
          MYAPP_RELEASE_STORE_PASSWORD: "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
          MYAPP_RELEASE_KEY_PASSWORD: "${{ secrets.ANDROID_KEY_PASSWORD }}"
          NEW_VERSION_CODE: ${{ env.VERSION_CODE }}
          NEW_VERSION_NAME: ${{ env.VERSION_NAME }}
        run: |
          # MODO DETECTIVE: Listar archivos para ver si existe el Gemfile
          echo "Contenido de la carpeta actual:"
          ls -la
          
          # 1. Instalar bundler
          gem install bundler --user-install
          export PATH=$PATH:/home/runner/.local/share/gem/ruby/3.2.0/bin
          
          # 2. Intentar instalar
          if [ -f "Gemfile" ]; then
            echo "Gemfile encontrado, instalando..."
            bundle install
            bundle exec fastlane upload_internal
          else
            echo "¡ERROR CRÍTICO! No se encontró el archivo Gemfile en esta carpeta."
            exit 1
          fi